### ISSUE TITLE
Can you explain a bit about how you convert the postgres driver and why

### ISSUE THREAD

**Issue by johnsonjsyuen** [cloudflare/worker-template-postgres#3]
Can you explain a bit about how you convert the postgres driver and why?
Will this change in the future by becoming unnecessary?
Can this be done to any JS library?

thanks in advance.

**Comment by hansottowirtz** [comment]
Had the same question a couple of days ago. This repo uses the postgres Deno module, which relies on Deno's `crypto` module, which uses WebAssembly. So the "conversion" here is just extracting that WebAssembly file (which is embedded in the Deno Javascript file) into a separate file. 

But in my module I modify the files so that it will just use the crypto constant that is available in every Cloudflare Worker instead of Deno's `crypto`, so no WebAssembly file is needed.

Please give it a try here: https://github.com/bubblydoo/cloudflare-workers-postgres-client
